### PR TITLE
Add default port for API Swagger docs

### PR DESCRIPTION
**Pull request by kb2ma**
The `swagger-docs` target to the top level makefile builds the docs and makes them [available](https://github.com/balena-os/balena-engine/blob/7c55ded8bb99ebdf7e39e6a6026a1838ab05aa99/Makefile#L129) on localhost port 9000. Add the port number to the README.

### CODE REVIEW

**Comment by lmbarros** [comment]
The ideal would be to try to get this merged upstream and then get the change via a merge or cherry-pick (to avoid diverging from Moby, and thus simplifying merges). Doesn't look like a controversial thing, so I guess this has a reasonable chance of being accepted. 

What do you think, @kb2ma ?

**Comment by kb2ma** [comment]
I didn't realize this came directly from upstream. Sure, sounds like a worthwhile experiment. Let me first be sure my force-push fixes the error.

**Comment by kb2ma** [comment]
@lmbarros , the build has failed a couple of times now on the "Is custom" check. Have you seen this error before? Any idea on how to fix it?

**Comment by lmbarros** [comment]
I don't recall seeing this before, @kb2ma . Our last commit on this repo was almost 2 months ago. Maybe a flowzone regression created over this period?

**Comment by kb2ma** [comment]
Created moby/moby#46781, so closing this one.

**Pull request closed without merging**
