### PR TITLE
meta: housekeeping

### PR DESCRIPTION
**Pull request by robertgzr**
* codeowners
* issue/pr templates
* s/resin/balena/
* nested changelogs

### CODE REVIEW

**Comment by robertgzr** [comment]
@balena-ci retest

**Comment by robertgzr** [comment]
hmm it shouldn't after https://github.com/balena-io/balena-versionist/pull/38, I'll have a look

**Comment by robertgzr** [comment]
looks like it's just not using 0.12.2 which has my changes

**Comment by robertgzr** [comment]
but I found more problems: 

* this PR adds a CHANGELOG.yml to support nested changelogs, the versions in there still get the leading zero stipped
* so do the versions written to CHANGELOG

**Comment by robertgzr** [comment]
ran the CHANGELOG.yml through js-yaml, opened https://github.com/balena-io/balena-versionist/pull/40 for the remaining versioning issues

**Comment by robertgzr** [comment]
@balena-ci retest

**Comment by robertgzr** [comment]
@balena-ci retest

**Comment by roman-mazur** [comment]
Converted to draft while we are figuring out the build issues (just playing with VB functionality - feel free to convert back when neccessary).

It looks like CI image change was not good.

**Comment by robertgzr** [comment]
@balena-ci retest

**Pull request merged**
