### PR TITLE
Update balenaEngine to 18.09

### PR DESCRIPTION
**Pull request by robertgzr**
Replaces #150 

- [x] unit tests
- [x] integration tests
- [x] compare binary sizes

|  Architecture | 17.13.3 | 18.09.3 |   %    |                                                                                                                               
|---------------|---------|---------|--------|
| x86           | 30.4MB  | 39.5MB  | +30% |
| aarch64       | 27.9MB  | 36.9MB  | +32% |
| arm           | 25.1MB  | 33.4MB  | +33% |

- [x] build on:
	- [x] x86_64
	- [x] armv7 (after removing `-buildmode=pie`)
	- [x] aarch64 (~~blocked until `balenalib/aarch64-golang:1.10.8` is available~~, switched to using `balenalib/raspberrypi3-64-golang`)
- [ ] fix versionist fails on upstream commits (https://github.com/balena-io/versionist/issues/133, https://github.com/balena-io/resin-commit-lint/issues/30)
- [ ] calculate new versions on top of `18.09.3`
- [x] include [this](https://github.com/docker/docker-ce/blob/18.09/CHANGELOG.md) in the generated changelog for this PR

#### Notes for deployment in balenaOS
- do we want to have containerd managed by systemd?
- change default address pool according to https://github.com/balena-os/balena-libnetwork/pull/6 using `--default-address-pool` option

### CODE REVIEW

**Comment by robertgzr** [comment]
Having some issues with the non-x86 builds, looks like it's because of the new `-buildmode=pie` flag that is used now.

I am checking without and would move forward if that's ok

cc @petrosagg

**Comment by robertgzr** [comment]
Needs a change to versionist to ignore external commits and we need to add a file like `UPSTREAM_VERSION` to start versioning balenaEngine at `18.09.3`

**Comment by robertgzr** [comment]
After updating to 18.09 balenaEngine will no longer manage containerd, instead this is left to systemd.
This probably requires some changes to the way we deploy things in balenaOS

cc @ZubairLK @agherzan

**Comment by agherzan** [comment]
@robertgzr why is that? 18.09.3-ce seems to manage containerd on a host I have.

**Comment by robertgzr** [comment]
@agherzan nvm this is related to upstream packaging https://github.com/docker/docker-ce-packaging/pull/131

Still good to keep the release notes in mind https://docs.docker.com/engine/release-notes/#18090

Could this make our life's earlier for  balena-os/meta-balena#1391

**Comment by robertgzr** [comment]
@petrosagg regarding storage driver support... 

`aufs` is still supported on 18.09 but is not the default anymore (`overlay2` is). `overlay` and `devicemapper` are deprecated.

**Comment by robertgzr** [comment]
This is the range of new commits that go on top of the merged in ones from upstream:
https://github.com/balena-os/balena-engine/pull/151/files/19a131bcb8a35dbd1dc267c028908d835760661e..49810dc78e6865f2305969616245160e4df9460d

Things that I see as worthy of some attention:
- engine <-> containerd : while containerd is still started/stopped by the engine if we go with the current way of deploying it, upstream has moved to having containerd be managed by systemd
- [buildkit integration](https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066)

**Comment by pdcastro** [comment]
@robertgzr, great work! But even the subset of 8 commits that _"go on top of the merged in ones from upstream"_ is still 75,000 lines of code. So I'm not sure if usual code review applies, and perhaps the focus should be on: _"Does it work?"_ :-) To this end maybe what we need is a testing plan. Some thoughts:

* In Flowdock you explained that you have run the docker integration tests without failure, "but that's just x86_64" and you would like Travis to run them for all architectures. So let's get that sorted. CC: @nazrhom, @jviotti 
* I was thinking whether we could have a BoB release with the new balenaEngine, so people could use it as their dev env for a couple of weeks, and see how it behaves. CC: @hedss 
* I don't know if it's too much, but maybe as a one-off we could have two releases of balenaOS that are mostly identical except for balenaEngine. That way we and even customers who are willing to give it a go could tentatively adopt the new balenaEngine image, while having a fallback alternative. CC: @shaunmulligan, @agherzan, @ZubairLK for thoughts.
* We (dev team) should test it on our Raspberry Pis. Maybe a Flowdock PSA when the balenaOS image is ready.

Then again, maybe it's not that bad. If the integration tests pass, it's already a big step!

**Comment by robertgzr** [comment]
@pdcastro sounds like a plan :)

> I was thinking whether we could have a BoB release with the new balenaEngine, so people could use it as their dev env for a couple of weeks

+1, sounds like the most solid way to test that this has no quirks that come to bite us later

> we could have two releases of balenaOS that are mostly identical except for balenaEngine

this is going along with the BoB testing, no? we would need a balenaOS release with 18.09 for that... given we don't change too much about the rest of the OS dropping in 17.13 shouldn't be that big of an issue

> If the integration tests pass, it's already a big step!

and I have been running it just fine on a Raspbian-based Pi (pihole/webserver/netdata containers) for the last few weeks

**Comment by hedss** [comment]
> I was thinking whether we could have a BoB release with the new balenaEngine, so people could use it as their dev env for a couple of weeks, and see how it behaves.

This sounds like a good idea to me, but it's not so much a BoB release as a version of the OS with this version in which we can run BoB on. But, I guess it's going to sit on Staging a while first?

**Comment by petrosagg** [comment]
@hedss @pdcastro yeah, we don't need to do dual release. We'll do test on staging and also our device release tests before putting in production. So let's get this moving forward :)

**Comment by robertgzr** [comment]
@petrosagg I think you have to merge this

**Pull request merged**
