### PR TITLE
patch: Add balena-engine documentation

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Moving balena-engine docs from balena-site 

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by lmbarros** [comment]
Hi @vipulgupta2048 ! Thanks a lot for working on this! That's another move in the right direction, IMHO!

The PR looks fine to me, but IIUC, we need more work on Flowzone so that we can have the Engine docs automatically updated in balena.io, right? (Well, and we also need to migrate the Engine repo to use Flowzone, of course!)

So, maybe this PR should remain a draft until we are ready to merge it without duplicating content between this repo and balena-site?

**Comment by vipulgupta2048** [comment]
Agreed, this PR also needs more work so yeah.

**Comment by lmbarros** [comment]
> What's the blockers for engine getting flowzone? Is that something actively being worked on?

I spent a couple of days in it to check if it was an easy win, and it wasn't (My PR: #305). I currently have no plans to try this again soon.

I see that Page did a couple of attempts yesterday (#312), but they seem to have failed too. I don't know if he intends to keep looking into this.

**Comment by lmbarros** [comment]
I don't know what exactly is failing, BTW. In my case, IIRC, building was working when I ran my docker-compose locally, but failing when running on Github. My initial hunch was that it was because the build uses docker-in-docker and something was missing to make it work. (But this is just an unchecked guess from my side.)

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Pull request merged**
