### PR TITLE
Update Moby to 20.10.17; containerd to 1.6.6; runc to 1.1.2

### LINKED ISSUE #300: Should update to moby v20.10.13 to get containerd v1.5.10
See: https://github.com/moby/moby/blob/v20.10.13/hack/dockerfile/install/containerd.installer#L18

### PR DESCRIPTION
**Pull request by lmbarros**
The main motivation for this PR is to update containerd to the 1.6 release (as the version currently bundled with balenaOS, 1.4, [is EOL](https://containerd.io/releases/)). The following components were updated:

* Moby to 20.10.17 (which the Moby release using the containerd version we wanted)
* containerd to 1.6.6
* runc to 1.1.2
* All of these components own dependencies

The PR as a whole is huge, but most of its bulk comes wither from commits merged from upstream Moby or from the one commit re-vendoring the dependencies. All other commits created by me are comparatively simple. I suggest reviewing the commits individually.

**Testing:**

* All unit tests are passing. A number of integration tests of the "CLI suite" are failing, but they are all regressions introduced during our latest major update (this is being tracked here: #309). In other words, all tests that were passing after the initial 20.10 upgrade are still passing.
* Built OS for a Pi Zero, ran a stress test app for ~22 hours during which:
    * Ran ~10 app updates.
    * Measured the time needed to run a `balena info` and start a hello-world container. No performance differences found compared to the current balenaEngine release.
* I created a [draft PR in meta-balena](https://github.com/balena-os/meta-balena/pull/2846) using this branch, to check for integration side effects. All passes -- except for the `qemu-generic-aarch64` tests which are currently unstable. (Anyway, I ran the `os`, `e2e`, and `hup` suites locally for `qemu-generic-aarch64` and they passed)
* We also created a [draft PR in balena-raspberrrypi](https://github.com/balena-os/balena-raspberrypi/pull/980) for running the automated test suite on actual devices. We had some failures there, but nothing that appeared to be related with the Engine.

Resolves #300 

Unblocks:
* https://github.com/balena-io/environment-production/pull/761
* https://github.com/balena-io/balena-builder/pull/1006
* https://github.com/balena-io/balena-cloud/pull/1004

### CODE REVIEW

**Comment by lmbarros** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@lmbarros the changes look good to me - I skipped the upstream and vendor refactoring, and scanned though your integration ones. The update is clean and well structured.
I am wondering how best to test it so we don't introduce nasty regressions. I am thinking you should maybe branch `balena-raspberrypi` with this update and launch some leviathan jobs on all supported device types.
It would also be good to do some manual checks in the RPI0 to see how performance is. We may also want to leave a couple of devices running some application to make sure everything is smooth.
What do you think?

**Comment by lmbarros** [comment]
Thanks @alexgg ! I have a [branch on meta-balena](https://github.com/balena-os/meta-balena/pull/2846) that I created to leverage the OS tests.  I think I never got all tests there to pass on a single run, but every time I checked it was caused by one of the few known cases of flaky OS tests.

I'll do more extensive tests running on a device. (So far I have just tried very basic things, like starting a container.)

**Comment by ab77** [comment]
@lmbarros any updates on this? We have a non-functional engine in balena-builder right now.

cc @Page- @thgreasi

**Comment by lmbarros** [comment]
It's ongoing, @ab77 . This update has broken our aarch64 CI tests, apparently because of the AppArmor config on the kernel used for generic-aarch64. This specif point is being discussed here: https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/qemu-generic-aarch64.20and.20AppArmor

**Comment by lmbarros** [comment]
What's wrong with the Engine on balena-builder now?

**Comment by lmbarros** [comment]
> Is there a quick way we can build the binaries for v19.03.16 manually?

Tried a quick local build of this release and it failed (didn't dig into why, apparently some dependencies weren't found).

Why do you need this version specifically? It's almost 2 years old.

Why did you asked about this specific PR? If this PR would work for you, a newer Engine version should work, too.

**Comment by ab77** [comment]
@lmbarros this is the last builder commit known to work: https://github.com/balena-io/balena-builder/commit/d6af534f0cb9c5733b5a1a095bea70894a9c8aa2

It contains engine build from the commit I posted.

**Comment by ab77** [comment]
@lmbarros I've manually adjusted the pre-release and testing it:
https://github.com/balena-os/balena-engine/releases/tag/v20.10.28

**Review by ab77 — APPROVED** [review]
See Zulip thread.

**Pull request merged**
