### PR TITLE
18.x: Clean up leaked engine data

### PR DESCRIPTION
**Pull request by roman-mazur**
Cherry-pick of #203 for the master branch.

### CODE REVIEW

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
@robertgzr balenaCI does not seem to run the actual build

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by robertgzr** [comment]
> @robertgzr balenaCI does not seem to run the actual build

image

It does?

**Comment by roman-mazur** [comment]
It didn't when I wrote the comment :)

**Comment by roman-mazur** [comment]
@curcuz @Bucknalla CI now builds PRs with balenaCloud builders:
https://ci.balena-dev.com/builds/1456783#L5e9f0b7d:7025

**Comment by roman-mazur** [comment]
@robertgzr A friendly ping: it's good to merge and bump balenaEngine version.

**Pull request merged**
