### PR TITLE
Fix container data deletion

### PR DESCRIPTION
**Pull request by roman-mazur**
The previous implementation was not comparing graphdriver content to layerStore mounts.

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by roman-mazur** [comment]
It looks like the balenaCI build check is not set as required for the project.

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
Updated to also acquire the mounts map lock.

**Comment by robertgzr** [comment]
looks good

```
---> Making bundle: .integration-daemon-setup (in bundles/test-integration)
---> Making bundle: .ensure-emptyfs (in bundles/test-integration)
Running integration-test (iteration 1)
Running /go/src/github.com/docker/docker/integration/hostapp
INFO: Testing against a local daemon
=== RUN   TestBareRuntime
--- PASS: TestBareRuntime (0.03s)
=== RUN   TestMobynitMountContainer
--- PASS: TestMobynitMountContainer (1.70s)
	daemon.go:291: [dc78e627c3cd0] waiting for daemon to start
	daemon.go:323: [dc78e627c3cd0] daemon started
	daemon.go:281: [dc78e627c3cd0] exiting daemon
PASS
```

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Pull request merged**
