### PR TITLE
installer: download to file, resume download

### PR DESCRIPTION
**Pull request by glensc**
Ensures that download is complete before the file is attempted to unpack.

Fixes https://github.com/balena-os/balena-engine/issues/199

### CODE REVIEW

**Comment by robertgzr** [comment]
I don't really want to download to `/var/tmp` on all platforms...

but I also can't reproduce this error (tried alpine and ubuntu)

**Comment by glensc** [comment]
updated to use the same target path. 

as for reproducer, you need your download to be interrupted obviously.

**Comment by glensc** [comment]
Obviously, I didn't add 517 commits to this branch, somebody force-pushed over my changes.

I t think my original commits where (can be cherry-picked):
- 507dc4f19c9f40ef38fa74bf1428de6cd2fad12d
- 74a042fdade88b34a4632c56f6301f7d050697b5

**Comment by glensc** [comment]
And mu change wasn't to change `/var/tmp` to download path, but rather to same directory as target: `/usr/local/bin`

**Comment by ab77** [comment]
@glensc if you are still interested in contributing, could you please rebase on master and add only the changes, so that they can be reviewed. cc @lmbarros

**Comment by glensc** [comment]
@ab77 no I'm not interested. but you may be interested as they are good changes?

**Pull request closed without merging**
