### PR TITLE
Backport platform-detection fixes from containerd

### PR DESCRIPTION
**Pull request by robertgzr**
See https://github.com/containerd/containerd/pull/4530
and `git log ad25c1a9c34361e4071f508b9a91946b05fce165^..2055e12953bb538228d8d9fe627fa545d7cf82be ./platforms/`
in the containerd repo

also drop some vendored packages that we don't need since we remove swarm, I was getting errors from the cloudfoundry one when bumping the containerd vendor

### CODE REVIEW

**Comment by robertgzr** [comment]
ran the integration tests (minus cli suite) locally before pushing this up

**Comment by robertgzr** [comment]
oh and this would fix #269

**Comment by robertgzr** [comment]
hmm unit tests are failing on the fact that by default we run the `daemon/cluster` tests as well... and those import the `swarmkit` package

**Comment by robertgzr** [comment]
is this too much :sweat_smile:

**Comment by robertgzr** [comment]
@klutchell this would be the changeset in the containerd repo: https://github.com/balena-os/balena-containerd/compare/balena-os:73f499182d4c052e5f104d4f881ab96583f58a82%5E...19.03-balena

this pr just pulls that in, the swarm/cluster commits are more difficult as they exclusively delete engine code

**Comment by lmbarros** [comment]
@robertgzr , I looked at the code changes and they look good to me. However, I think it would be better to split the removal of unused vendored code to a different PR. This would be easier to rollback or revisit in the future (and also less intimidating and less prone to oversights for reviewers.)

**Comment by robertgzr** [comment]
@lmbarros hmm I get the visibility concerns, although splitting this into another pr won't really help us with that since github will still print a huge number of deleted lines because of the vendor change and the containerd changes only amount two a 1 line diff in this repo. I probably should have PR'd the backport over in https://github.com/balena-os/balena-containerd to make the review process smoother

imo reverting would be a commit level operation and shouldn't depend on the number of pr's we do this in

**Comment by lmbarros** [comment]
@robertgzr Yes, makes sense. I think you are right. I'll give another look to this PR just to be sure and approve it if I still can't find any issues.

**Review by lmbarros — APPROVED** [review]

**Pull request merged**
